SELECT * FROM BRANCH;-- 29
SELECT * FROM CONVERSION_RATE;-- 624
SELECT * FROM COUNTRY;--21
SELECT * FROM CURRENCY_LOOKUP;--21
SELECT * FROM EURO_CONVERSION;--8
SELECT * FROM INVENTORY_LEVELS;--53730
SELECT * FROM ORDER_DETAILS;--446023
SELECT * FROM ORDER_HEADER;--53267
SELECT * FROM ORDER_METHOD;-- 7
SELECT * FROM PRODUCT;--274
SELECT * FROM PRODUCT_BRAND;--28
SELECT * FROM PRODUCT_COLOR_LOOKUP;--27
SELECT * FROM PRODUCT_FORECAST;--129096
SELECT * FROM PRODUCT_LINE;--5
SELECT * FROM PRODUCT_NAME_LOOKUP;--6302
SELECT * FROM PRODUCT_SIZE_LOOKUP;--55
SELECT * FROM PRODUCT_TYPE;--21
SELECT * FROM RETURNED_ITEM;--10249
SELECT * FROM RETURN_REASON;--5
SELECT * FROM SALES_REGION;--5
SELECT * FROM SALES_TARGET;--233625
SELECT * FROM TIME_DIMENSION;--1465
SELECT * FROM TIME_QUARTER_LOOKUP;--20
SELECT * FROM XGOREV;--17
